export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const SET_SITE_NAME = "SET_SITE_NAME";
export const SET_LOCAL_CONTEST = "SET_LOCAL_CONTEST";
